TOuchableOpacity -> Text
SocialGouv/ozensemble pull request #61
Opened 2022-05-24 13:53 UTC by laurestph

2022-05-24 14:54 UTC, arnaudambro requested changes

2022-05-24 15:01 UTC, laurestph commented on src/scenes/Health/Conseil/ToHelpMeReduce.js
> +            <Text
Le touchableOpacity mettait du margin en dessous 
En mettant que text ça fixe le problème

2022-05-24 15:08 UTC, arnaudambro commented on src/scenes/Health/Conseil/ToHelpMeReduce.js
> +            <Text
ok
et `TouchableWithoutFeedback` ? ça devrait marcher avec
(et `import { TouchableOpacity } from 'react-native'`)

2022-05-24 15:23 UTC, laurestph commented on src/scenes/Health/Conseil/ToHelpMeReduce.js
> +            <Text
<img width="377" alt="Screenshot 2022-05-24 at 17 22 08" src="https://user-images.githubusercontent.com/70069314/170072930-e800022b-b60e-409d-8777-24daac8efd6b.png">

2022-05-24 15:24 UTC, laurestph commented on src/scenes/Health/Conseil/ToHelpMeReduce.js
> +            <Text
Avec TouchableWithoutFeedback il y a aussi le décalage

2022-05-25 06:13 UTC, arnaudambro commented on src/scenes/Health/Conseil/ToHelpMeReduce.js
> +            <Text
ok !

2022-05-25 06:13 UTC, merged